services:
    Shopping\ApiTKDtoMapperBundle\Service\ArrayHelper: ~
    Shopping\ApiTKDtoMapperBundle\Service\StringHelper: ~

    Shopping\ApiTKDtoMapperBundle\EventListener\ControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Shopping\ApiTKDtoMapperBundle\EventListener\SwaggerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    Shopping\ApiTKDtoMapperBundle\EventListener\MapperListener:
        arguments:
            - '@Shopping\ApiTKDtoMapperBundle\EventListener\ControllerListener'
            - '@annotations.reader'
            - '@Shopping\ApiTKDtoMapperBundle\Service\ArrayHelper'
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.view, priority: 1000 }

    Shopping\ApiTKDtoMapperBundle\Handler\PhpViewHandler: ~

    Shopping\ApiTKDtoMapperBundle\Serializer\DtoEncoder:
        tags:
            - { name: serializer.encoder }

    Shopping\ApiTKDtoMapperBundle\Describer\AnnotationDescriber:
        public: false
        arguments:
            - '@nelmio_api_doc.routes.default'
            - '@Shopping\ApiTKCommonBundle\Util\ControllerReflector'
            - '@annotations.reader'
            - '@Shopping\ApiTKDtoMapperBundle\Service\StringHelper'
        tags:
            - { name: 'nelmio_api_doc.route_describer', priority: -2000 }
